- name: Create kata repo
  hosts: all
  remote_user: kata
  tasks:
  - name: Create rsync config
    become: true
    copy:
      dest: /etc/rsyncd.conf
      content: |
        lock file = /var/run/rsync.lock
        log file = /var/log/rsyncd.log
        pid file = /var/run/rsyncd.pid
        [kata]
              path = /home/kata/go/src/github.com/kata-containers
              comment = kata repo
              read only = no
              uid = kata
              gid = kata
  - name: Create kata directory
    file:
      path: /home/kata/go/src/github.com/kata-containers/kata-containers
      state: directory
  - name: Create kata tests directory
    file:
      path: /home/kata/go/src/github.com/kata-containers/tests
      state: directory
  - name: Start rsyncd service
    become: true
    systemd:
      name: rsync
      state: started
      enabled: True
  - name: Synchronize kata-containers repo 
    synchronize:
      src: "{{ lookup('env','HOME') }}/go/src/github.com/kata-containers/kata-containers"  
      dest: rsync://kata@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/kata
      recursive: yes
  - name: Synchronize tests repo
    synchronize:
      src: "{{ lookup('env','HOME') }}/go/src/github.com/kata-containers/tests"  
      dest: rsync://kata@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/kata
      recursive: yes
  - name: Disable swap to run k8s tests
    command: swapoff -a
    become: true
  - name: Clean-up Agent dir
    command:
      cmd: make clean
      chdir: /home/kata/go/src/github.com/kata-containers/kata-containers/tools/osbuilder
  - name: Clean cni dir
    file:
      path: /etc/cni/net.d
      state: absent
    become: true
  - name: Clean kube directory
    file:
      path: /home/kata/.kube
      state: absent
    become: true
  - name: Run Kata CI job
    environment:
      WORKSPACE: "/home/kata"
      CI_JOB: "CRIO_K8S"
    command:
      cmd: ./jenkins_job_build.sh github.com/kata-containers/kata-containers &> /home/kata/kata_ci_job.log
      chdir: /home/kata/go/src/github.com/kata-containers/tests/.ci
    async: 1000
    poll: 0
    register: ci_register
  - name: Check CI job every 120 sec
    async_status:
      jid: "{{ ci_register.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    delay: 120
    retries: 30
    ignore_errors: yes
  - name: Copy log file locally
    fetch:
      src: /home/kata/kata_ci_job.log
      dest: kata-ci-job.log
